language: node_js
sudo: false
node_js:
  - stable
install:
  - npm install -g istanbul
  - npm install -g codecov
  - npm install
script:
  - npm test
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter test -- -R spec
  - codecov
